run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - gofmt
    - goimports
    - misspell
    - nilerr
    - nolintlint
    - revive
    - wastedassign

issues:
  exclude-dirs:
    - z
  exclude-rules:
    - linters:
        - gosec
        - structcheck
        - unused
      text: "`data` is unused"
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - revive
      text: "empty-block:"
    - linters:
        - revive
      text: "var-naming:"
    - linters:
        - revive
      text: "unused-parameter:"
    - linters:
        - revive
      text: "exported:"
    - linters:
        - revive
      text: "redefines-builtin-id:"
    - path: ldt/profiles\.go
      linters:
        - misspell
    - path: _test\.go
      linters: # security is not make sense in tests
        - deadcode
        - errcheck
        - errorlint
        - revive
        - staticcheck
        - wastedassign
