run:
  timeout: 5m
  skip-dirs: z

linters:
  enable:
    - asciicheck
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - gofmt
    - goimports
    - gosec
    - misspell
    - nilerr
    - nolintlint
    - revive
    - wastedassign

issues:
  exclude-rules:
    - linters:
        - structcheck
        - unused
      text: "`data` is unused"
    - linters:
        - staticcheck
      text: "SA1019:"
    - linters:
        - revive
      text: "empty-block:"
    - linters:
        - revive
      text: "var-naming:"
    - linters:
        - revive
      text: "unused-parameter:"
    - linters:
        - revive
      text: "exported:"
    - path: _test\.go
      linters: # security is not make sense in tests
        - deadcode
        - errcheck
        - errorlint
        - gosec
        - revive
        - staticcheck
        - wastedassign
