name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-go@v5
        with:
          go-version: '^1.16'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          args: --verbose

  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ['1.16', '1.17', '1.18', '1.19', '1.20', '1.21']
        include:
          - os: ubuntu-latest
            go-build: ~/.cache/go-build
    name: ${{ matrix.os }} @ Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - uses: actions/cache@v4.0.2
        with:
          path: |
            ${{ matrix.go-build }}
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Run Tests
        run: go test -covermode=atomic -coverprofile=coverage.out $(go list ./...)

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          flags: ${{ matrix.os }},go-${{ matrix.go }}
